name: state_app_samples
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  build_runner: ^2.10.4

  # MobX Dependencies
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # MobX dependecy for code generator
  mobx_codegen: ^2.0.0

flutter:
  uses-material-design: true